// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/00dc7c1c629c3fd5e92a56afc87efda571d84e22/cordova-ionic/cordova-ionic.d.ts
// Type definitions for Ionic Cordova plugins
// Project: https://github.com/driftyco
// Definitions by: Hendrik Maus <https://github.com/hendrikmaus>
// Definitions: https://github.com/borisyankov/DefinitelyTyped


interface CordovaPlugins {
  Keyboard:Ionic.Keyboard;
}